import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import ThemeSwitcher from '../components/ThemeSwitcher'
import Link from 'next/link'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-zinc-50 dark:bg-black`}
      >
        <ThemeProvider attribute="class">
          <header className="w-full">
            <div className="flex items-center justify-between h-16 px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
              <h1 className="text-2xl font-bold text-black dark:text-white">
                <Link href="/">AI Agent</Link>
              </h1>
              <div className="flex items-center">
                <ThemeSwitcher />
                <Link
                  href="/settings"
                  className="text-sm font-medium text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white"
                >
                  Settings
                </Link>
              </div>
            </div>
          </header>
          <main className="flex flex-col flex-1">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
